apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  type: LoadBalancer  # Puedes cambiarlo a NodePort si lo prefieres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

